#:schema node_modules/wrangler/config-schema.json
name = "xieerfan-blog-worker"
main = "index.js" 
compatibility_date = "2026-02-17"

# 1. 修正后的 R2 绑定（避开 ASSETS 保留字）
[[r2_buckets]]
binding = "MY_R2"
bucket_name = "xieerfan-assets"

# 2. 绑定 D1 数据库 (保持不变)
[[d1_databases]]
binding = "BLOG_DB"
database_name = "xieerfan-blog"
database_id = "c843e2fa-c9ac-447c-8ed4-6c23ff014bb0"

[[d1_databases]]
binding = "WIKI_DB"
database_name = "xieerfan-wiki"
database_id = "7badd5d6-47f1-48b3-aa74-ced673c07803"

